name: Generate Static Site

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]
    branches: [ main ]

jobs:
  build:
    runs-on: macos-15

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v5
      with:
        lfs: 'true'
    - name: Build & run (Generate Site)
      run: swift run
    - name: Export Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Site
        path: Output/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v5
      with:
        name: Site
        path: Output/
    - name: copy file to server
      uses: appleboy/scp-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        passphrase: ${{ secrets.PRIVATE_KEY_PASSPHRASE }}
        strip_components: 1
        overwrite: true
        tar_tmp_path: "~/"
        source: "Output/"
        target: "/var/www/oliverbinns.co.uk/public_html/"
