name: Generate Static Site

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build
    - name: Run (Generate Site)
      run: swift run
    - name: Export Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Site
        path: Output/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: Site
        path: Output/
    - name: copy file to server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        passphrase: ${{ secrets.PRIVATE_KEY_PASSPHRASE }}
        strip_components: 1
        overwrite: true
        source: "Output/"
        target: "/var/www/oliverbinns.co.uk/public_html"
